name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.74
          profile: minimal
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v1.2.0
      - run: make setup
      - run: make test
